from zoo.libs.maya import zapi
from zoo.libs.hive import constants
from collections import OrderedDict

GUIDE_ATTRS = OrderedDict(
    (
        (constants.ID_ATTR, dict(Type=zapi.attrtypes.kMFnDataString,
                                 default="",
                                 name=constants.ID_ATTR,
                                 channelBox=False,
                                 keyable=False, locked=True)),
        (constants.ISGUIDE_ATTR, dict(Type=zapi.attrtypes.kMFnNumericBoolean,
                                      default=True,
                                      value=True,
                                      name=constants.ISGUIDE_ATTR,
                                      channelBox=False,
                                      keyable=False,
                                      locked=True)),
        (constants.DISPLAYAXISSHAPE_ATTR, dict(Type=zapi.attrtypes.kMFnNumericBoolean,
                                               default=False,
                                               name=constants.DISPLAYAXISSHAPE_ATTR,
                                               channelBox=True,
                                               keyable=False, locked=False)),
        (constants.AUTOALIGN_ATTR, dict(Type=zapi.attrtypes.kMFnNumericBoolean,
                                        default=True,
                                        name=constants.AUTOALIGN_ATTR,
                                        channelBox=True,
                                        keyable=False, locked=False)),
        (constants.MIRROR_ATTR, dict(Type=zapi.attrtypes.kMFnNumericBoolean, default=True,
                                     name=constants.MIRROR_ATTR,
                                     channelBox=True,
                                     keyable=False,
                                     locked=False)),
        (constants.MIRROR_BEHAVIOUR_ATTR, dict(Type=zapi.attrtypes.kMFnkEnumAttribute,
                                               name=constants.MIRROR_BEHAVIOUR_ATTR,
                                               enums=constants.MIRROR_BEHAVIOURS_TYPES,
                                               keyable=False,
                                               channelBox=True,
                                               default=0,
                                               value=0)),
        (constants.AUTOALIGNUPVECTOR_ATTR, dict(Type=zapi.attrtypes.kMFnNumeric3Float,
                                                channelBox=True,
                                                locked=False,
                                                name=constants.AUTOALIGNUPVECTOR_ATTR,
                                                keyable=False,
                                                default=constants.DEFAULT_UP_VECTOR)),
        (constants.AUTOALIGNAIMVECTOR_ATTR, dict(Type=zapi.attrtypes.kMFnNumeric3Float,
                                                 channelBox=True,
                                                 locked=False,
                                                 name=constants.AUTOALIGNAIMVECTOR_ATTR,
                                                 keyable=False,
                                                 default=constants.DEFAULT_AIM_VECTOR)),
        (constants.PIVOTSHAPE_ATTR, dict(Type=zapi.attrtypes.kMFnDataString,
                                         channelBox=False,
                                         name=constants.PIVOTSHAPE_ATTR,
                                         keyable=False)),
        (constants.PIVOTCOLOR_ATTR, dict(Type=zapi.attrtypes.kMFnNumeric3Float,
                                         channelBox=False,
                                         name=constants.PIVOTCOLOR_ATTR,
                                         keyable=False)),
        (constants.GUIDESHAPE_ATTR, dict(Type=zapi.attrtypes.kMFnMessageAttribute,
                                         name=constants.GUIDESHAPE_ATTR)),
        (constants.GUIDESNAP_PIVOT_ATTR, dict(Type=zapi.attrtypes.kMFnMessageAttribute,
                                              name=constants.GUIDESNAP_PIVOT_ATTR)),
        (constants.GUIDE_SHAPE_PRIMARY_ATTR, dict(Type=zapi.attrtypes.kMFnMessageAttribute,
                                                  name=constants.GUIDE_SHAPE_PRIMARY_ATTR,
                                                  isArray=True))

    )

)
