ZOO_SEL_ORDER = {"light": 3,
                 "locator": 3,
                 "nurbsCurve": 11,
                 "nurbsSurface": 3,
                 "polymesh": 3,
                 "polymeshEdge": 12,
                 "polymeshFace": 13,
                 "polymeshUV": 14,
                 "polymeshVertex": 14,
                 "camera": 3,
                 "isoparm": 12,
                 "controlVertex": 12,
                 "surfaceEdge": 12,
                 "surfaceFace": 12,
                 "lattice": 3,
                 "latticePoint": 12,
                 "follicle": 3,
                 "cluster": 3
                 }
